import sublime
import sublime_plugin
from ..protocol import Diagnostic as Diagnostic, DocumentHighlight as DocumentHighlight, DocumentUri, FoldingRange as FoldingRange, SignatureHelpTriggerKind
from .code_actions import CodeActionOrCommand as CodeActionOrCommand, CodeActionsByConfigName as CodeActionsByConfigName, actions_manager as actions_manager
from .code_lens import LspToggleCodeLensesCommand as LspToggleCodeLensesCommand
from .completion import QueryCompletionsTask as QueryCompletionsTask
from .core.constants import CODE_ACTION_ANNOTATION_SCOPE as CODE_ACTION_ANNOTATION_SCOPE, DOCUMENT_HIGHLIGHT_KIND_SCOPES as DOCUMENT_HIGHLIGHT_KIND_SCOPES, HOVER_ENABLED_KEY as HOVER_ENABLED_KEY, RegionKey as RegionKey, RequestFlags as RequestFlags, SIGNATURE_HELP_ACTIVE_PARAMETER_SCOPE as SIGNATURE_HELP_ACTIVE_PARAMETER_SCOPE, SIGNATURE_HELP_FUNCTION_SCOPE as SIGNATURE_HELP_FUNCTION_SCOPE, SIGNATURE_HELP_INACTIVE_PARAMETER_SCOPE as SIGNATURE_HELP_INACTIVE_PARAMETER_SCOPE, ST_VERSION as ST_VERSION
from .core.logging import debug as debug
from .core.open import open_in_browser as open_in_browser
from .core.panels import PanelName as PanelName
from .core.protocol import Request as Request
from .core.registry import best_session as best_session, get_position as get_position, windows as windows
from .core.sessions import AbstractViewListener as AbstractViewListener, Session as Session, SessionBufferProtocol as SessionBufferProtocol
from .core.settings import userprefs as userprefs
from .core.signature_help import SigHelp as SigHelp, SignatureHelpStyle as SignatureHelpStyle
from .core.types import ClientConfig as ClientConfig, FEATURES_TIMEOUT as FEATURES_TIMEOUT, SettingsRegistration as SettingsRegistration, basescope2languageid as basescope2languageid, debounced as debounced
from .core.url import parse_uri as parse_uri, view_to_uri as view_to_uri
from .core.views import MarkdownLangMap as MarkdownLangMap, diagnostic_severity as diagnostic_severity, document_highlight_key as document_highlight_key, first_selection_region as first_selection_region, format_code_actions_for_quick_panel as format_code_actions_for_quick_panel, format_diagnostic_for_html as format_diagnostic_for_html, make_link as make_link, range_to_region as range_to_region, show_lsp_popup as show_lsp_popup, text_document_identifier as text_document_identifier, text_document_position_params as text_document_position_params, update_lsp_popup as update_lsp_popup
from .core.windows import WindowManager as WindowManager
from .diagnostics import get_diagnostics_identifiers as get_diagnostics_identifiers
from .folding_range import folding_range_to_range as folding_range_to_range
from .hover import code_actions_content as code_actions_content
from .session_buffer import SessionBuffer as SessionBuffer
from .session_view import SessionView as SessionView
from _typeshed import Incomplete
from typing import Any, Callable, Iterable, Literal, TypeVar, overload
from typing_extensions import Concatenate, ParamSpec
from weakref import WeakValueDictionary

P = ParamSpec('P')
R = TypeVar('R')

def requires_session(func: Callable[Concatenate[DocumentSyncListener, P], R]) -> Callable[Concatenate[DocumentSyncListener, P], R | None]:
    """
    A decorator for the `DocumentSyncListener` event handlers, which immediately returns `None` if there are no
    `SessionView`s.
    """
def is_regular_view(v: sublime.View) -> bool: ...

class TextChangeListener(sublime_plugin.TextChangeListener):
    ids_to_listeners: WeakValueDictionary[int, TextChangeListener]
    @classmethod
    def is_applicable(cls, buffer: sublime.Buffer) -> bool: ...
    view_listeners: Incomplete
    def __init__(self) -> None: ...
    def attach(self, buffer: sublime.Buffer) -> None: ...
    def detach(self) -> None: ...
    def on_text_changed(self, changes: Iterable[sublime.TextChange]) -> None: ...
    def on_reload_async(self) -> None: ...
    def on_revert_async(self) -> None: ...

class DocumentSyncListener(sublime_plugin.ViewEventListener, AbstractViewListener):
    ACTIVE_DIAGNOSTIC: str
    debounce_time = FEATURES_TIMEOUT
    @classmethod
    def applies_to_primary_view_only(cls) -> bool: ...
    hover_provider_count: int
    def __init__(self, view: sublime.View) -> None: ...
    def __del__(self) -> None: ...
    def on_post_move_window_async(self) -> None: ...
    def on_documentation_popup_toggle(self, *, opened: bool) -> None: ...
    def on_session_initialized_async(self, session: Session) -> None: ...
    def on_session_shutdown_async(self, session: Session) -> None: ...
    def get_diagnostics_async(self, location: sublime.Region | int, max_diagnostic_severity_level: int = ...) -> list[tuple[SessionBufferProtocol, list[Diagnostic]]]: ...
    def on_diagnostics_updated_async(self, is_view_visible: bool) -> None: ...
    def session_buffers_async(self, capability: str | None = None) -> list[SessionBuffer]: ...
    def session_views_async(self) -> list[SessionView]: ...
    def on_text_changed_async(self, change_count: int, changes: Iterable[sublime.TextChange]) -> None: ...
    def get_uri(self) -> DocumentUri: ...
    def set_uri(self, new_uri: DocumentUri) -> None: ...
    def get_language_id(self) -> str: ...
    def get_request_flags(self, session: Session) -> RequestFlags: ...
    def on_load_async(self) -> None: ...
    def on_post_move_async(self) -> None: ...
    def on_activated_async(self) -> None: ...
    def on_selection_modified_async(self) -> None: ...
    def on_post_save_async(self) -> None: ...
    def on_close(self) -> None: ...
    def on_query_context(self, key: str, operator: int, operand: Any, match_all: bool) -> bool | None: ...
    def on_hover(self, point: int, hover_zone: int) -> None: ...
    def on_text_command(self, command_name: str, args: dict | None) -> tuple[str, dict] | None: ...
    def on_post_text_command(self, command_name: str, args: dict[str, Any] | None) -> None: ...
    def on_query_completions(self, prefix: str, locations: list[int]) -> sublime.CompletionList | None: ...
    @overload
    def do_signature_help_async(self, trigger_kind: Literal[SignatureHelpTriggerKind.TriggerCharacter], trigger_char: str) -> None: ...
    @overload
    def do_signature_help_async(self, trigger_kind: Literal[SignatureHelpTriggerKind.Invoked, SignatureHelpTriggerKind.ContentChange], trigger_char: None = None) -> None: ...
    def navigate_signature_help(self, forward: bool) -> None: ...
    def handle_code_action_select(self, config_name: str, actions: list[CodeActionOrCommand], index: int) -> None: ...
    def session_async(self, capability: str, point: int | None = None) -> Session | None: ...
    def sessions_async(self, capability: str | None = None) -> list[Session]: ...
    def session_by_name(self, name: str | None = None) -> Session | None: ...
    def get_capability_async(self, session: Session, capability_path: str) -> Any | None: ...
    def has_capability_async(self, session: Session, capability_path: str) -> bool: ...
    def purge_changes_async(self) -> None: ...
    def trigger_on_pre_save_async(self) -> None: ...
    def revert_async(self) -> None: ...
    def reload_async(self) -> None: ...
