from LSP.plugin.core.types import ClientConfig
from typing import Any
from unittesting import DeferrableTestCase

test_file_path: str

def read_client_config(name: str, d: dict[str, Any]) -> ClientConfig: ...
def update_client_config(external_config: ClientConfig, user_override_config: dict[str, Any]) -> ClientConfig: ...

class ConfigParsingTests(DeferrableTestCase):
    def test_can_parse_settings_with_selector(self) -> None: ...
    def test_can_update_config(self) -> None: ...
    def test_can_read_experimental_capabilities(self) -> None: ...
    def test_transport_config_extends_env_path(self) -> None: ...
    def test_disabled_capabilities(self) -> None: ...
    def test_filter_out_disabled_capabilities_ignore_partially(self) -> None: ...
    def test_exposes_unknown_root_keys(self) -> None: ...
    def test_shallow_merges_overrides_for_unknown_root_keys(self) -> None: ...
    def test_attribute_access_prefers_native_keys(self) -> None: ...
    def test_does_not_have_subscription_access(self) -> None: ...
    def test_path_maps(self) -> None: ...
