import unittest

class TestDiff(unittest.TestCase):
    def test_add(self) -> None: ...
    def test_remove(self) -> None: ...
    def test_add_and_remove(self) -> None: ...
    def test_with_sets(self) -> None: ...
    def test_with_more_sets(self) -> None: ...
    def test_completely_new(self) -> None: ...

class TestDocumentSelector(unittest.TestCase):
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def test_language(self) -> None: ...
    def test_pattern_basics(self) -> None: ...
    def test_pattern_asterisk(self) -> None:
        """`*` to match one or more characters in a path segment."""
    def test_pattern_optional(self) -> None:
        """`?` to match on one character in a path segment."""
    def test_pattern_globstar(self) -> None:
        """`**` to match any number of path segments, including none."""
    def test_pattern_grouping(self) -> None:
        """`{}` to group conditions (e.g. `**/*.{ts,js}` matches all TypeScript and JavaScript files)."""
    def test_pattern_character_range(self) -> None:
        """
        `[]` to declare a range of characters to match in a path segment (e.g., `example.[0-9]` to match on
        `example.0`, `example.1`, …).
        """
    def test_pattern_negated_character_range(self) -> None:
        """
        `[!...]` to negate a range of characters to match in a path segment (e.g., `example.[!0-9]` to match on
        `example.a`, `example.b`, but not `example.0`).
        """
    def test_base_scope_to_language_id_mappings(self) -> None: ...
