import sublime
import unittest
from LSP.plugin.core.signature_help import SignatureHelpStyle
from LSP.protocol import SignatureHelp

class SignatureHelpTest(unittest.TestCase):
    view: sublime.View
    style: SignatureHelpStyle
    def setUp(self) -> None: ...
    def test_no_signature(self) -> None: ...
    def test_empty_signature_list(self) -> None: ...
    def assert_render(self, signature_input: SignatureHelp, regex: str) -> None: ...
    def test_signature(self) -> None: ...
    def test_markdown(self) -> None: ...
    def test_second_parameter(self) -> None: ...
    def test_parameter_ranges(self) -> None: ...
    def test_overloads(self) -> None: ...
    def test_dockerfile_signature(self) -> None: ...
