import sublime
import unittest
from .test_mocks import TEST_CONFIG as TEST_CONFIG
from LSP.plugin.core.promise import Promise
from LSP.plugin.core.protocol import Error
from LSP.plugin.core.sessions import Logger, Manager, Session
from LSP.plugin.core.types import ClientConfig
from LSP.protocol import Diagnostic as Diagnostic, DocumentUri, LogMessageParams, MessageActionItem as MessageActionItem, ShowMessageParams, ShowMessageRequestParams
from typing import Any, Generator
from weakref import WeakSet

class MockManager(Manager):
    def __init__(self, window: sublime.Window) -> None: ...
    def window(self) -> sublime.Window: ...
    def sessions(self, view: sublime.View, capability: str | None = None) -> Generator[Session, None, None]: ...
    def get_session(self, config_name: str, file_path: str) -> Session | None: ...
    def get_project_path(self, file_name: str) -> str | None: ...
    def should_ignore_diagnostics(self, uri: DocumentUri, configuration: ClientConfig) -> str | None: ...
    def start_async(self, configuration: ClientConfig, initiating_view: sublime.View) -> None: ...
    def on_post_exit_async(self, session: Session, exit_code: int, exception: Exception | None) -> None: ...
    def on_diagnostics_updated(self) -> None: ...
    def handle_message_request(self, config_name: str, params: ShowMessageRequestParams) -> Promise[MessageActionItem | None]: ...
    def handle_show_message(self, config_name: str, params: ShowMessageParams) -> Promise[MessageActionItem | None]: ...
    def handle_log_message(self, config_name: str, params: LogMessageParams) -> None: ...
    def handle_stderr_log(self, config_name: str, message: str) -> None: ...

class MockLogger(Logger):
    def stderr_message(self, message: str) -> None: ...
    def outgoing_response(self, request_id: Any, params: Any) -> None: ...
    def outgoing_error_response(self, request_id: Any, error: Error) -> None: ...
    def outgoing_request(self, request_id: int, method: str, params: Any, blocking: bool) -> None: ...
    def outgoing_notification(self, method: str, params: Any) -> None: ...
    def incoming_response(self, request_id: int | None, params: Any, is_error: bool, blocking: bool) -> None: ...
    def incoming_request(self, request_id: Any, method: str, params: Any) -> None: ...
    def incoming_notification(self, method: str, params: Any, unhandled: bool) -> None: ...

class MockSessionBuffer:
    session: Session
    session_views: WeakSet[Any]
    mock_uri: str
    mock_language_id: str
    def __init__(self, session: Session, mock_uri: str, mock_language_id: str) -> None: ...
    @property
    def last_synced_version(self) -> int: ...
    def get_uri(self) -> DocumentUri | None: ...
    def get_language_id(self) -> str | None: ...
    def register_capability_async(self, registration_id: str, capability_path: str, registration_path: str, options: dict[str, Any]) -> None: ...
    def unregister_capability_async(self, registration_id: str, capability_path: str, registration_path: str) -> None: ...
    def on_diagnostics_async(self, raw_diagnostics: list[Diagnostic], version: int) -> None: ...

class SessionTest(unittest.TestCase):
    def test_experimental_capabilities(self) -> None: ...
    def test_initialize_params(self) -> None: ...
    def test_document_sync_capabilities(self) -> None: ...
    def test_get_session_buffer_for_uri_with_nonfiles(self) -> None: ...
    def test_get_session_buffer_for_uri_with_files(self) -> None: ...
