from .setup import TextDocumentTestCase as TextDocumentTestCase, expand as expand
from LSP.plugin import FileWatcher, FileWatcherEvent as FileWatcherEvent, FileWatcherEventType as FileWatcherEventType, FileWatcherProtocol
from LSP.plugin.core.types import ClientConfig
from typing import Generator

def setup_workspace_folder() -> str: ...

class TestFileWatcher(FileWatcher):
    active_watchers: list[TestFileWatcher]
    @classmethod
    def create(cls, root_path: str, patterns: list[str], events: list[FileWatcherEventType], ignores: list[str], handler: FileWatcherProtocol) -> TestFileWatcher: ...
    root_path: str
    patterns: list[str]
    events: list[FileWatcherEventType]
    ignores: list[str]
    handler: FileWatcherProtocol
    def __init__(self, root_path: str, patterns: list[str], events: list[FileWatcherEventType], ignores: list[str], handler: FileWatcherProtocol) -> None: ...
    def destroy(self) -> None: ...
    def trigger_event(self, events: list[FileWatcherEvent]) -> None: ...

class FileWatcherDocumentTestCase(TextDocumentTestCase):
    """
    Changes TextDocumentTestCase behavior so that the initialization and destroy of the config
    and the view happens before and after every test rather than per-testsuite.
    """
    @classmethod
    def setUpClass(cls) -> None: ...
    @classmethod
    def tearDownClass(cls) -> None: ...
    folder_root_path: str
    def setUp(self) -> Generator: ...
    def tearDown(self) -> Generator: ...

class FileWatcherStaticTests(FileWatcherDocumentTestCase):
    @classmethod
    def get_stdio_test_config(cls) -> ClientConfig: ...
    def test_initialize_params_includes_capability(self) -> None: ...
    def test_creates_static_watcher(self) -> None: ...
    def test_handles_file_event(self) -> Generator: ...

class FileWatcherDynamicTests(FileWatcherDocumentTestCase):
    def test_handles_dynamic_watcher_registration(self) -> Generator: ...
    def test_aggregates_multiple_registrations_with_common_kind_and_base(self) -> Generator: ...
    def test_does_not_aggregate_non_matching_base(self) -> Generator: ...
