import sublime
from LSP.plugin.core.windows import WindowManager
from unittesting import DeferrableTestCase

class LspServerPanelTests(DeferrableTestCase):
    window: sublime.Window
    wm: WindowManager | None
    view: sublime.View | None
    panel: sublime.View | None
    def setUp(self) -> None: ...
    def assert_total_lines_equal(self, expected_total_lines: int) -> None: ...
    def update_panel(self, msg: str) -> None: ...
    def test_server_panel_circular_behavior(self) -> None: ...
