from .setup import TextDocumentTestCase as TextDocumentTestCase
from .test_single_document import TEST_FILE_PATH as TEST_FILE_PATH
from LSP.plugin.core.protocol import Point
from LSP.protocol import PublishDiagnosticsParams, Range
from _typeshed import Incomplete
from collections.abc import Generator

TEST_FILE_URI: Incomplete

def create_test_diagnostics(diagnostics: list[tuple[str, Point, Point]], version: int | None = None) -> PublishDiagnosticsParams: ...
def range_from_points(start: Point, end: Point) -> Range: ...

class DiagnosticsTestCase(TextDocumentTestCase):
    def test_clear_diagnostics_immediately_after_change(self) -> Generator: ...
    def test_ignores_publish_diagnostics_version(self) -> Generator: ...
    def test_handles_unknown_tag_gracefully(self) -> Generator: ...
    def test_handles_multiple_tags(self) -> Generator: ...
