import unittest

class PatternToGlobTests(unittest.TestCase):
    def test_basic_directory_patterns(self) -> None: ...
    def test_complex_directory_patterns(self) -> None: ...
    def test_basic_file_patterns(self) -> None: ...
    def test_complex_file_patterns(self) -> None: ...
    def test_slash_star_or_star_slash_matches_any_directory(self) -> None: ...
    def test_question_mark_not_matches_slash_in_basic_pattern(self) -> None: ...
    def test_question_mark_matches_slash_in_complex_pattern(self) -> None: ...
    def test_project_relative_patterns(self) -> None: ...

class PatternToGlobWindowsTests(unittest.TestCase):
    def test_project_relative_directory_pattern_forward_slash_root(self) -> None: ...
    def test_project_relative_file_pattern_forward_slash_root(self) -> None: ...
    def test_project_relative_nested_pattern_forward_slash_root(self) -> None: ...
    def test_project_relative_directory_pattern_backslash_root(self) -> None: ...
    def test_project_relative_file_pattern_backslash_root(self) -> None: ...
    def test_project_relative_without_root_path(self) -> None: ...
