from .setup import TextDocumentTestCase as TextDocumentTestCase
from typing import Any, Callable, Generator
from unittest import TestCase

additional_edits: dict[str, Any]

class CompletionsTestsBase(TextDocumentTestCase):
    @classmethod
    def init_view_settings(cls) -> None: ...
    def type(self, text: str) -> None: ...
    def move_cursor(self, row: int, col: int) -> None: ...
    def create_commit_completion_closure(self, commit_completion_command: str = 'commit_completion') -> Callable[[], bool]: ...
    def select_completion(self) -> Generator: ...
    def shift_select_completion(self) -> Generator: ...
    def read_file(self) -> str: ...
    def verify(self, *, completion_items: list[dict[str, Any]], insert_text: str, expected_text: str) -> Generator: ...

class QueryCompletionsTests(CompletionsTestsBase):
    def test_none(self) -> Generator: ...
    def test_simple_label(self) -> Generator: ...
    def test_prefer_insert_text_over_label(self) -> Generator: ...
    def test_prefer_text_edit_over_insert_text(self) -> Generator: ...
    def test_simple_insert_text(self) -> Generator: ...
    def test_var_prefix_using_label(self) -> Generator: ...
    def test_var_prefix_added_in_insertText(self) -> Generator:
        """
        https://github.com/sublimelsp/LSP/issues/294.

        User types '$env:U', server replaces '$env:U' with '$env:USERPROFILE'
        """
    def test_pure_insertion_text_edit(self) -> Generator:
        """
        https://github.com/sublimelsp/LSP/issues/368.

        User types '$so', server returns pure insertion completion 'meParam', completing it to '$someParam'.

        THIS TEST FAILS
        """
    def test_space_added_in_label(self) -> Generator:
        '''Clangd: label=" const", insertText="const" (https://github.com/sublimelsp/LSP/issues/368).'''
    def test_dash_missing_from_label(self) -> Generator:
        '''
        Powershell: label="UniqueId", trigger="-UniqueIdd, text to be inserted = "-UniqueId".

        (https://github.com/sublimelsp/LSP/issues/572)
        '''
    def test_edit_before_cursor(self) -> Generator:
        """https://github.com/sublimelsp/LSP/issues/536."""
    def test_edit_after_nonword(self) -> Generator:
        """https://github.com/sublimelsp/LSP/issues/645."""
    def test_filter_text_is_not_a_prefix_of_label(self) -> Generator:
        '''
        Metals: "Implement all members".

        The filterText is \'e\', so when the user types \'e\', one of the completion items should be
        "Implement all members".

        VSCode doesn\'t show the filterText in this case; it\'ll only show "Implement all members".
        c.f. https://github.com/microsoft/language-server-protocol/issues/898#issuecomment-593968008

        In SublimeText, we always show the filterText (a.k.a. trigger).

        This is one of the more confusing and contentious completion items.

        https://github.com/sublimelsp/LSP/issues/771
        '''
    def test_additional_edits_if_session_has_the_resolve_capability(self) -> Generator: ...
    def test_prefix_should_include_the_dollar_sign(self) -> Generator: ...
    def test_fuzzy_match_plaintext_insert_text(self) -> Generator: ...
    def test_fuzzy_match_plaintext_text_edit(self) -> Generator: ...
    def test_fuzzy_match_snippet_insert_text(self) -> Generator: ...
    def test_fuzzy_match_snippet_text_edit(self) -> Generator: ...
    def verify_multi_cursor(self, completion: dict[str, Any]) -> Generator:
        """
        Check whether `fd` gets replaced by `fmod` when the cursor is at `fd|`.
        Turning the `d` into an `m` is an important part of the test.
        """
    def test_multi_cursor_plaintext_insert_text(self) -> Generator: ...
    def test_multi_cursor_plaintext_text_edit(self) -> Generator: ...
    def test_multi_cursor_snippet_insert_text(self) -> Generator: ...
    def test_multi_cursor_snippet_text_edit(self) -> Generator: ...
    def test_nontrivial_text_edit_removal(self) -> Generator: ...
    def test_nontrivial_text_edit_removal_with_buffer_modifications_clangd(self) -> Generator: ...
    def test_nontrivial_text_edit_removal_with_buffer_modifications_json(self) -> Generator: ...
    def test_text_edit_plaintext_with_multiple_lines_indented(self) -> Generator[None, None, None]: ...
    def test_insert_insert_mode(self) -> Generator: ...
    def test_replace_insert_mode(self) -> Generator: ...
    def test_show_deprecated_flag(self) -> None: ...
    def test_show_deprecated_tag(self) -> None: ...
    def test_strips_carriage_return_in_insert_text(self) -> Generator: ...
    def test_strips_carriage_return_in_text_edit(self) -> Generator: ...
    def test_label_details_with_filter_text(self) -> None: ...
    def test_label_details_without_filter_text(self) -> None: ...

class QueryCompletionsNoResolverTests(CompletionsTestsBase):
    """
    The difference between QueryCompletionsTests and QueryCompletionsNoResolverTests
    is that QueryCompletionsTests has the completion item resolve capability enabled
    and the QueryCompletionsNoResolverTests has the resolve capability disabled.
    """
    @classmethod
    def get_test_server_capabilities(cls) -> dict: ...
    def test_additional_edits_if_session_does_not_have_the_resolve_capability(self) -> Generator: ...

class ItemDefaultTests(TestCase):
    def test_respects_defaults_for_completion(self) -> None: ...
    def test_defaults_should_not_override_completion_fields_if_present(self) -> None: ...
    def test_conversion_of_edit_range_to_text_edit_when_it_includes_insert_replace_fields(self) -> None: ...

class FormatCompletionsUnitTests(TestCase):
    def test_label(self) -> None: ...
    def test_detail(self) -> None: ...
    def test_label_details(self) -> None: ...
    def test_label_details_2(self) -> None: ...
    def test_label_details_3(self) -> None: ...
    def test_label_details_4(self) -> None: ...
    def test_label_details_5(self) -> None: ...
    def test_filter_text_1(self) -> None: ...
    def test_filter_text_2(self) -> None: ...
    def test_filter_text_3(self) -> None: ...
    def test_filter_text_4(self) -> None: ...
    def test_filter_text_and_label_details_1(self) -> None: ...
    def test_filter_text_and_label_details_3(self) -> None: ...
    def test_filter_text_and_label_details_4(self) -> None: ...
