import sublime
from _typeshed import Incomplete

class ProgressReporter:
    title: Incomplete
    def __init__(self, title: str) -> None: ...
    def __del__(self) -> None: ...
    def __call__(self, message: str | None, percentage: None | int | float) -> None: ...

class ViewProgressReporter(ProgressReporter):
    def __init__(self, view: sublime.View, key: str, title: str, message: str | None = None, percentage: None | int | float = None) -> None: ...
    def __del__(self) -> None: ...
    def __call__(self, message: str | None = None, percentage: None | int | float = None) -> None: ...

class WindowProgressReporter(ProgressReporter):
    def __init__(self, window: sublime.Window, key: str, title: str, message: str | None = None, percentage: None | int | float = None) -> None: ...
    def __del__(self) -> None: ...
    def __call__(self, message: str | None = None, percentage: None | int | float = None) -> None: ...

class ApplicationProgressReporter(ProgressReporter):
    def __init__(self, key: str, title: str, message: str | None = None, percentage: None | int | float = None) -> None: ...
    def __del__(self) -> None: ...
    def __call__(self, message: str | None = None, percentage: None | int | float = None) -> None: ...
