import sublime
from .collections import DottedDict as DottedDict
from .logging import debug as debug
from .types import ClientConfig as ClientConfig, Settings as Settings, SettingsRegistration as SettingsRegistration, debounced as debounced, read_dict_setting as read_dict_setting
from _typeshed import Incomplete
from abc import ABC, abstractmethod

SERVER_CONFIGS_FILENAME: str

class LspSettingsChangeListener(ABC):
    @abstractmethod
    def on_client_config_updated(self, config_name: str | None = None) -> None: ...
    @abstractmethod
    def on_server_settings_changed(self, config_name: str, settings: DottedDict) -> None: ...
    @abstractmethod
    def on_userprefs_updated(self) -> None: ...

class ClientConfigs:
    all: Incomplete
    external: Incomplete
    def __init__(self) -> None: ...
    def add_for_testing(self, config: ClientConfig) -> None: ...
    def remove_for_testing(self, config: ClientConfig) -> None: ...
    def add_external_config(self, name: str, settings_path: str, notify_listener: bool) -> bool: ...
    def remove_external_config(self, name: str) -> None: ...
    def update_configs(self) -> None: ...
    def update_config(self, name: str, config: ClientConfig) -> None: ...
    def on_server_settings_changed(self, name: str, settings: DottedDict) -> None: ...
    def enable(self, config_name: str) -> None: ...
    def disable(self, config_name: str) -> None: ...
    def set_listener(self, listener: LspSettingsChangeListener) -> None: ...

client_configs: Incomplete

def load_settings() -> None: ...
def unload_settings() -> None: ...
def userprefs() -> Settings: ...
def globalprefs() -> sublime.Settings: ...
