import sublime
from ...protocol import Position, Range
from .protocol import TextPosition as TextPosition

def point_to_offset(view: sublime.View, point: TextPosition) -> int: ...
def position_to_offset(view: sublime.View, position: Position) -> int: ...
def range_to_region(view: sublime.View, lsp_range: Range) -> sublime.Region: ...
