import sublime
from ...protocol import (
    Diagnostic as Diagnostic,
    DocumentUri,
    FileCreate as FileCreate,
    FileDelete as FileDelete,
    FileRename as FileRename,
    LogMessageParams,
    MessageActionItem as MessageActionItem,
    ShowMessageParams,
    ShowMessageRequestParams,
)
from ..api import (
    AbstractPlugin as AbstractPlugin,
    IsApplicableContext as IsApplicableContext,
    LspPlugin as LspPlugin,
    OnPreStartContext as OnPreStartContext,
    PluginStartError as PluginStartError,
    get_plugin as get_plugin,
)
from .configurations import (
    RETRY_COUNT_TIMEDELTA as RETRY_COUNT_TIMEDELTA,
    RETRY_MAX_COUNT as RETRY_MAX_COUNT,
    WindowConfigChangeListener as WindowConfigChangeListener,
    WindowConfigManager as WindowConfigManager,
)
from .constants import MESSAGE_TYPE_LEVELS as MESSAGE_TYPE_LEVELS
from .logging import debug as debug, exception_log as exception_log
from .message_request_handler import MessageRequestHandler as MessageRequestHandler
from .panels import (
    LOG_LINES_LIMIT_SETTING_NAME as LOG_LINES_LIMIT_SETTING_NAME,
    MAX_LOG_LINES_LIMIT_OFF as MAX_LOG_LINES_LIMIT_OFF,
    MAX_LOG_LINES_LIMIT_ON as MAX_LOG_LINES_LIMIT_ON,
    PanelManager as PanelManager,
    PanelName as PanelName,
)
from .promise import Promise as Promise
from .protocol import Error as Error, Notification as Notification, Point as Point
from .sessions import (
    AbstractViewListener as AbstractViewListener,
    Logger as Logger,
    Manager as Manager,
    Session as Session,
)
from .settings import (
    LspSettingsChangeListener as LspSettingsChangeListener,
    client_configs as client_configs,
    userprefs as userprefs,
)
from .tree_view import TreeViewSheet as TreeViewSheet
from .types import (
    ClientConfig as ClientConfig,
    ViewStatusHandler as ViewStatusHandler,
    match_file_operation_filters as match_file_operation_filters,
    matches_pattern as matches_pattern,
    sublime_pattern_to_glob as sublime_pattern_to_glob,
)
from .url import parse_uri as parse_uri
from .views import (
    diagnostic_severity as diagnostic_severity,
    extract_variables as extract_variables,
    format_diagnostic_for_panel as format_diagnostic_for_panel,
    make_link as make_link,
)
from .workspace import (
    ProjectFolders as ProjectFolders,
    WorkspaceFolder as WorkspaceFolder,
    sorted_workspace_folders as sorted_workspace_folders,
)
from typing import Any, Generator

def set_diagnostics_count(view: sublime.View, errors: int, warnings: int) -> None: ...

class WindowManager(Manager, WindowConfigChangeListener, ViewStatusHandler):
    panel_manager: PanelManager | None
    tree_view_sheets: dict[str, TreeViewSheet]
    formatters: dict[str, str]
    suppress_sessions_restart_on_project_update: bool
    total_error_count: int
    total_warning_count: int
    def __init__(
        self,
        window: sublime.Window,
        workspace: ProjectFolders,
        config_manager: WindowConfigManager,
    ) -> None: ...
    @property
    def window(self) -> sublime.Window: ...
    @property
    def workspace_folders(self) -> list[WorkspaceFolder]: ...
    def get_and_clear_server_log(self) -> list[tuple[str, str]]: ...
    def get_config_manager(self) -> WindowConfigManager: ...
    def get_sessions(self) -> Generator[Session, None, None]: ...
    def on_load_project_async(self) -> None: ...
    def on_post_save_project_async(self) -> None: ...
    def update_workspace_folders_async(self) -> None: ...
    def enable_config_async(self, config_name: str) -> None: ...
    def disable_config_async(self, config_name: str) -> None: ...
    def register_listener_async(self, listener: AbstractViewListener) -> None: ...
    def unregister_listener_async(self, listener: AbstractViewListener) -> None: ...
    def listeners(self) -> Generator[AbstractViewListener, None, None]: ...
    def listener_for_view(self, view: sublime.View) -> AbstractViewListener | None: ...
    def recheck_is_applicable_async(
        self, view: sublime.View, config_name: str
    ) -> None: ...
    def get_session(
        self, config_name: str, file_path: str | None = None
    ) -> Session | None: ...
    def start_async(
        self, config: ClientConfig, initiating_view: sublime.View
    ) -> None: ...
    def handle_message_request(
        self, config_name: str, params: ShowMessageRequestParams
    ) -> Promise[MessageActionItem | None]: ...
    def restart_sessions_async(self, config_names: list[str]) -> None: ...
    def get_project_path(self, file_path: str) -> str | None: ...
    def should_ignore_diagnostics(
        self, uri: DocumentUri, configuration: ClientConfig
    ) -> str | None: ...
    def on_post_exit_async(
        self, session: Session, exit_code: int, exception: Exception | None
    ) -> None: ...
    def destroy(self) -> None:
        """
        Called **from the main thread** when the plugin unloads. In that case we must destroy all sessions
        from the main thread. That could lead to some dict/list being mutated while iterated over, so be careful.
        """
    def handle_log_message(
        self, config_name: str, params: LogMessageParams
    ) -> None: ...
    def handle_stderr_log(self, config_name: str, message: str) -> None: ...
    def handle_server_message_async(self, config_name: str, message: str) -> None: ...
    def log_server_message(self, config_name: str, message: str) -> None: ...
    def get_log_lines_limit(self) -> int: ...
    def is_log_lines_limit_enabled(self) -> bool: ...
    def handle_show_message(
        self, config_name: str, params: ShowMessageParams
    ) -> None: ...
    def on_diagnostics_updated(self) -> None: ...
    def update_diagnostics_panel_async(self) -> None: ...
    def notify_did_create_files(self, created_files: list[FileCreate]) -> None: ...
    def notify_did_rename_files(self, renamed_files: list[FileRename]) -> None: ...
    def notify_did_delete_files(self, deleted_files: list[FileDelete]) -> None: ...
    def on_configs_changed(self, configs: list[ClientConfig]) -> None: ...
    def on_server_settings_changed(self, configs: list[ClientConfig]) -> None: ...
    def on_view_status_changed(
        self, config_name: str, view: sublime.View, status: str | None
    ) -> None: ...

class WindowRegistry(LspSettingsChangeListener):
    def __init__(self) -> None: ...
    def enable(self) -> None: ...
    def disable(self) -> None: ...
    def lookup(self, window: sublime.Window | None) -> WindowManager | None: ...
    def listener_for_view(self, view: sublime.View) -> AbstractViewListener | None: ...
    def discard(self, window: sublime.Window) -> None: ...
    def on_client_config_updated(self, config_name: str | None = None) -> None: ...
    def on_userprefs_updated(self) -> None: ...

class RequestTimeTracker:
    def __init__(self) -> None: ...
    def start_tracking(
        self, request_id: int | str, *, server_initiated: bool
    ) -> None: ...
    def end_tracking(self, request_id: int | str, *, server_initiated: bool) -> str: ...
    @classmethod
    def formatted_now(cls) -> str: ...

class PanelLogger(Logger):
    def __init__(self, manager: WindowManager, server_name: str) -> None: ...
    def stderr_message(self, message: str) -> None:
        """
        Not handled here as stderr messages are handled by WindowManager regardless
        if this logger is enabled.
        """
    def log(self, message: str, params: Any) -> None: ...
    def outgoing_response(self, request_id: int | str, params: Any) -> None: ...
    def outgoing_error_response(self, request_id: int | str, error: Error) -> None: ...
    def outgoing_request(
        self, request_id: int | str, method: str, params: Any
    ) -> None: ...
    def outgoing_notification(self, method: str, params: Any) -> None: ...
    def incoming_response(
        self, request_id: int | str, params: Any, is_error: bool
    ) -> None: ...
    def incoming_request(
        self, request_id: int | str, method: str, params: Any
    ) -> None: ...
    def incoming_notification(
        self, method: str, params: Any, unhandled: bool
    ) -> None: ...

class RemoteLogger(Logger):
    PORT: int
    DIRECTION_OUTGOING: int
    DIRECTION_INCOMING: int
    def __init__(self, manager: WindowManager, server_name: str) -> None: ...
    def stderr_message(self, message: str) -> None: ...
    def outgoing_request(
        self, request_id: int | str, method: str, params: Any
    ) -> None: ...
    def incoming_response(
        self, request_id: int | str, params: Any, is_error: bool
    ) -> None: ...
    def incoming_request(
        self, request_id: int | str, method: str, params: Any
    ) -> None: ...
    def outgoing_response(self, request_id: int | str, params: Any) -> None: ...
    def outgoing_error_response(self, request_id: int | str, error: Error) -> None: ...
    def outgoing_notification(self, method: str, params: Any) -> None: ...
    def incoming_notification(
        self, method: str, params: Any, unhandled: bool
    ) -> None: ...

class RouterLogger(Logger):
    def __init__(self) -> None: ...
    def append(self, logger: Logger) -> None: ...
    def stderr_message(self, *args: Any, **kwargs: Any) -> None: ...
    def outgoing_response(self, *args: Any, **kwargs: Any) -> None: ...
    def outgoing_error_response(self, *args: Any, **kwargs: Any) -> None: ...
    def outgoing_request(self, *args: Any, **kwargs: Any) -> None: ...
    def outgoing_notification(self, *args: Any, **kwargs: Any) -> None: ...
    def incoming_response(self, *args: Any, **kwargs: Any) -> None: ...
    def incoming_request(self, *args: Any, **kwargs: Any) -> None: ...
    def incoming_notification(self, *args: Any, **kwargs: Any) -> None: ...
