import sublime
from ...protocol import WorkspaceFolder as LspWorkspaceFolder
from .types import diff as diff, matches_pattern as matches_pattern, sublime_pattern_to_glob as sublime_pattern_to_glob
from .url import filename_to_uri as filename_to_uri
from _typeshed import Incomplete

def is_subpath_of(file_path: str, potential_subpath: str) -> bool: ...

class WorkspaceFolder:
    name: Incomplete
    path: Incomplete
    def __init__(self, name: str, path: str) -> None: ...
    @classmethod
    def from_path(cls, path: str) -> WorkspaceFolder: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def to_lsp(self) -> LspWorkspaceFolder: ...
    def uri(self) -> str: ...
    def includes_uri(self, uri: str) -> bool: ...

class ProjectFolders:
    folders: Incomplete
    def __init__(self, window: sublime.Window) -> None: ...
    def update(self) -> bool: ...
    def includes_path(self, file_path: str) -> bool: ...
    def includes_excluded_path(self, file_path: str) -> bool:
        """
        Path is excluded if it's within one or more workspace folders and in at least one of the folders it's not
        excluded using `folder_exclude_patterns`.
        """
    def contains(self, view_or_file_name: str | sublime.View) -> bool: ...
    def get_workspace_folders(self) -> list[WorkspaceFolder]: ...

def sorted_workspace_folders(folders: list[str], file_path: str) -> list[WorkspaceFolder]: ...
def enable_in_project(window: sublime.Window, config_name: str) -> None: ...
def disable_in_project(window: sublime.Window, config_name: str) -> None: ...
